
    [[main]]
        url = "/"
        name = "首页"
        weight = 1
        pre = "internal"
        post = "home"
    [[main]]
        url = "/blogs/"
        name = "时间轴"
        weight = 2
        pre = "internal"
        post = "archive"
    [[main]]
        url = "/storys/"
        name = "随笔"
        weight = 3
        pre = "internal"
        post = "grav"
    [[main]]
         url = "/categories/"
         name = "分类"
         weight = 4
         pre = "internal"
         post = "th"
    [[main]]
        url = "/tags/"
         name = "标签"
         weight = 5
         pre = "internal"
         post = "tags"
    [[main]]
        url = "/links/"
        name = "链接"
        weight = 6
        pre = "internal"
        post = "link"
    [[main]]
        url = "/about/"
        name = "关于"
        weight = 7
        pre = "internal"
        post = "user-circle"


